### ISSUE TITLE
Saving the code, conversion to/from symbols, log, and exponental function

### ISSUE THREAD

**Issue by chairborne** [davidw/hecl#6]
One guy asked me to make an issue here. He wants to save his code into the file or "RMS" (dunno what is this). I actually do not use Hecl, but he really does not have an access to GitHub. He also wants you to add "conversion to  symbols from code and vice versa", dunno what does this mean too. And the last things he wants are logarithm and exponental function. Thanks.

**Comment by wkechel** [comment]
Arithmetic functions are already available but it depends on the MIDP/CLDC provided by the target hardware/software combination.

**Comment by chairborne** [comment]
He says there are only abs, ceil, cos, floor, random, sin, sqrt, and tan in the compiled MIDlet. Is there any kind of FFI?

**Comment by wkechel** [comment]
There is no FFI interface, bit the exponential functions are in the 
source code, so it is just a matter of compiling hecl properly for the 
target platform.

**Comment by chairborne** [comment]
Anyway, saving should be possible. RMS is an acronym for Rich Media Storage I guess.
